# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '123.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button_openfile = QtWidgets.QPushButton(self.centralwidget)
        self.button_openfile.setGeometry(QtCore.QRect(130, 450, 75, 23))
        self.button_openfile.setObjectName("button_openfile")
        self.button_pause = QtWidgets.QPushButton(self.centralwidget)
        self.button_pause.setGeometry(QtCore.QRect(240, 450, 75, 23))
        self.button_pause.setObjectName("button_pause")
        self.button_play = QtWidgets.QPushButton(self.centralwidget)
        self.button_play.setGeometry(QtCore.QRect(440, 450, 75, 23))
        self.button_play.setObjectName("button_play")
        self.button_stop = QtWidgets.QPushButton(self.centralwidget)
        self.button_stop.setGeometry(QtCore.QRect(340, 450, 75, 23))
        self.button_stop.setObjectName("button_stop")
        self.label_filepath = QtWidgets.QLabel(self.centralwidget)
        self.label_filepath.setGeometry(QtCore.QRect(50, 70, 131, 91))
        self.label_filepath.setObjectName("label_filepath")
        self.label_framecnt = QtWidgets.QLabel(self.centralwidget)
        self.label_framecnt.setGeometry(QtCore.QRect(300, 100, 131, 91))
        self.label_framecnt.setObjectName("label_framecnt")
        self.label_videoframe = QtWidgets.QLabel(self.centralwidget)
        self.label_videoframe.setGeometry(QtCore.QRect(500, 180, 131, 91))
        self.label_videoframe.setObjectName("label_videoframe")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_openfile.setText(_translate("MainWindow", "PushButton"))
        self.button_pause.setText(_translate("MainWindow", "PushButton"))
        self.button_play.setText(_translate("MainWindow", "PushButton"))
        self.button_stop.setText(_translate("MainWindow", "PushButton"))
        self.label_filepath.setText(_translate("MainWindow", "TextLabel"))
        self.label_framecnt.setText(_translate("MainWindow", "TextLabel"))
        self.label_videoframe.setText(_translate("MainWindow", "TextLabel"))



